# Generated by Django 4.0.6 on 2022-08-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_remove_customuser_age_remove_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
