# Generated by Django 4.0.6 on 2022-08-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_tool_description_tool_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
