# Generated by Django 4.0.6 on 2022-08-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_tool_price_alter_tool_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldetails',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
