# Generated by Django 4.0.6 on 2022-08-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_alter_rentaldetails_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldetails',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rentaldetails',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
