# Generated by Django 4.0.6 on 2022-08-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_alter_rentaldetails_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldetails',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
