# Generated by Django 4.0.6 on 2022-08-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_alter_rentaldetails_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldetails',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rentaldetails',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
