# Generated by Django 4.0.6 on 2022-08-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_alter_rentaldetails_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='status',
        ),
    ]
