# Generated by Django 4.0.6 on 2022-08-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_remove_tool_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentaldetails',
            name='status',
        ),
    ]
