# Generated by Django 4.0.6 on 2022-08-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_remove_rentaldetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaldetails',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentaldetails',
            name='total_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
